name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: macos-latest

    container:
      image: crystallang/crystal

    steps:
      - uses: actions/checkout@v2
      - name: Install GTK
        run: brew install gtk4
      - name: Install dependencies
        run: shards install
      - name: Run format check
        run: crystal tool format --check
      - name: Run ameba check
        run: bin/ameba