name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal

    steps:
      - uses: actions/checkout@v2
      - name: Install GI Repository
        run: apt install libgirepository1.0-dev
      - name: Install GLib
        run: apt install libglib2.0-dev
      - name: Install GObject
        run: apt install libgobject2.0-dev
      - name: Install dependencies
        run: shards install
      - name: Run format check
        run: crystal tool format --check
      - name: Run ameba check
        run: bin/ameba